name: Deploy preview

on:
  pull_request_target: null

jobs:
  deploy:
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Use node.js 14.15
        uses: actions/setup-node@v1
        with:
          node-version: 14.15
      - name: Build
        run: |
          npm ci && \
          node ./scripts/set-homepage.js /shlink-web-client/${GITHUB_HEAD_REF#refs/heads/} && \
          rm src/service-worker.ts && \
          npm run build
      - name: Deploy preview
        uses: shlinkio/deploy-preview-action@v1.0.1
        with:
          folder: build
