name: Build and publish docker image

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'

jobs:
  build:
    uses: shlinkio/github-actions/.github/workflows/docker-build-and-publish.yml@main
    secrets: inherit
    with:
      build-and-publish-script: bash ./scripts/docker/build
